### ISSUE TITLE
DatePicker calendarStyles prop (please add this to documents)

### ISSUE THREAD

**Issue by sinapcs** [evandhq/react-persian-datepicker#22] opened 2017-02-19 22:50 UTC
It was so hard to config datepicker without a good document.
if you want to add your css module to DatePicker you need to pass your object to calendarStyles prop. (I figured out this by reading source files of DatePicker component!)

in last part of documentation you mentioned that "the only thing that you will need to do is to require the css file that you made and pass it as styles prop to either Calendar or DatePicker". but it's wrong for DatePicker.

by the way thanks evands developers for this persian datepicker. It was harder for me to develop a persian date picker from scratch.

**I think the only thing this date picker needs is a good document.**

**Comment by mohebifar** [comment] 2017-02-20 21:24
Duplicate of #21. I'd be happy to accept a PR for that.

**Closed as completed by mohebifar** 2017-02-20 21:24 UTC
